//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkHourManagement_V1._2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPayPeriod
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string RO { get; set; }
        public string LaborHours { get; set; }
    }
}
